title: Taichi Aida
author: Taichi Aida
email: aida-taichi@ed.tmu.ac.jp
description: > # this means to ignore newlines until "baseurl:"
  
theme: minima

# social links
twitter_username: a1da_ # DO NOT include the @ character, or else the build will fail!
github_username:  a1da4 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
